service: expenses-app
provider:
  name: aws
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource: 'arn:aws:s3:::expenses-store'
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
          Resource: 'arn:aws:s3:::expenses-store/*'
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  memorySize: 256

functions:
  app:
    handler: build/src/handler.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true